[package]
name = "fwasm-examples"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
fwasm-sdk = { path = "../fwasm-sdk" }
codec = { workspace = true }
